//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BalanceAsset.
const (
	BalanceAssetEth  BalanceAsset = "eth"
	BalanceAssetUsdc BalanceAsset = "usdc"
)

// Valid indicates whether the value is a known member of the BalanceAsset enum.
func (e BalanceAsset) Valid() bool {
	switch e {
	case BalanceAssetEth:
		return true
	case BalanceAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for BalanceChain.
const (
	BalanceChainArbitrum BalanceChain = "arbitrum"
	BalanceChainBase     BalanceChain = "base"
)

// Valid indicates whether the value is a known member of the BalanceChain enum.
func (e BalanceChain) Valid() bool {
	switch e {
	case BalanceChainArbitrum:
		return true
	case BalanceChainBase:
		return true
	default:
		return false
	}
}

// Defines values for DepositAsset.
const (
	DepositAssetEth  DepositAsset = "eth"
	DepositAssetUsdc DepositAsset = "usdc"
)

// Valid indicates whether the value is a known member of the DepositAsset enum.
func (e DepositAsset) Valid() bool {
	switch e {
	case DepositAssetEth:
		return true
	case DepositAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for DepositChain.
const (
	DepositChainArbitrum DepositChain = "arbitrum"
	DepositChainBase     DepositChain = "base"
)

// Valid indicates whether the value is a known member of the DepositChain enum.
func (e DepositChain) Valid() bool {
	switch e {
	case DepositChainArbitrum:
		return true
	case DepositChainBase:
		return true
	default:
		return false
	}
}

// Defines values for DepositStatus.
const (
	DepositStatusOrphaned DepositStatus = "orphaned"
	DepositStatusPending  DepositStatus = "pending"
)

// Valid indicates whether the value is a known member of the DepositStatus enum.
func (e DepositStatus) Valid() bool {
	switch e {
	case DepositStatusOrphaned:
		return true
	case DepositStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DepositTier.
const (
	DepositTierObserved DepositTier = "observed"
	DepositTierOrphaned DepositTier = "orphaned"
	DepositTierSafe     DepositTier = "safe"
)

// Valid indicates whether the value is a known member of the DepositTier enum.
func (e DepositTier) Valid() bool {
	switch e {
	case DepositTierObserved:
		return true
	case DepositTierOrphaned:
		return true
	case DepositTierSafe:
		return true
	default:
		return false
	}
}

// Defines values for TransactionAsset.
const (
	TransactionAssetEth  TransactionAsset = "eth"
	TransactionAssetUsdc TransactionAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransactionAsset enum.
func (e TransactionAsset) Valid() bool {
	switch e {
	case TransactionAssetEth:
		return true
	case TransactionAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for TransactionChain.
const (
	TransactionChainArbitrum TransactionChain = "arbitrum"
	TransactionChainBase     TransactionChain = "base"
)

// Valid indicates whether the value is a known member of the TransactionChain enum.
func (e TransactionChain) Valid() bool {
	switch e {
	case TransactionChainArbitrum:
		return true
	case TransactionChainBase:
		return true
	default:
		return false
	}
}

// Defines values for TransferAsset.
const (
	TransferAssetEth  TransferAsset = "eth"
	TransferAssetUsdc TransferAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransferAsset enum.
func (e TransferAsset) Valid() bool {
	switch e {
	case TransferAssetEth:
		return true
	case TransferAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for TransferChain.
const (
	TransferChainArbitrum TransferChain = "arbitrum"
	TransferChainBase     TransferChain = "base"
)

// Valid indicates whether the value is a known member of the TransferChain enum.
func (e TransferChain) Valid() bool {
	switch e {
	case TransferChainArbitrum:
		return true
	case TransferChainBase:
		return true
	default:
		return false
	}
}

// Defines values for TransferRequestAsset.
const (
	Eth  TransferRequestAsset = "eth"
	Usdc TransferRequestAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransferRequestAsset enum.
func (e TransferRequestAsset) Valid() bool {
	switch e {
	case Eth:
		return true
	case Usdc:
		return true
	default:
		return false
	}
}

// Defines values for TransferRequestChain.
const (
	TransferRequestChainArbitrum TransferRequestChain = "arbitrum"
	TransferRequestChainBase     TransferRequestChain = "base"
)

// Valid indicates whether the value is a known member of the TransferRequestChain enum.
func (e TransferRequestChain) Valid() bool {
	switch e {
	case TransferRequestChainArbitrum:
		return true
	case TransferRequestChainBase:
		return true
	default:
		return false
	}
}

// Defines values for UnsupportedTokenObservationChain.
const (
	UnsupportedTokenObservationChainArbitrum UnsupportedTokenObservationChain = "arbitrum"
	UnsupportedTokenObservationChainBase     UnsupportedTokenObservationChain = "base"
)

// Valid indicates whether the value is a known member of the UnsupportedTokenObservationChain enum.
func (e UnsupportedTokenObservationChain) Valid() bool {
	switch e {
	case UnsupportedTokenObservationChainArbitrum:
		return true
	case UnsupportedTokenObservationChainBase:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	Asset BalanceAsset `json:"asset"`

	// Balance Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — to avoid float64 precision loss.
	Balance string       `json:"balance"`
	Chain   BalanceChain `json:"chain"`
}

// BalanceAsset defines model for Balance.Asset.
type BalanceAsset string

// BalanceChain defines model for Balance.Chain.
type BalanceChain string

// BalancesResponse defines model for BalancesResponse.
type BalancesResponse struct {
	Balances []Balance `json:"balances"`
}

// Customer defines model for Customer.
type Customer struct {
	CreatedAt time.Time `json:"createdAt"`

	// DepositAddress The customer's counterfactual CREATE2 deposit address (FR6, FR7, AD-8) — identical on every supported EVM chain. Computed once at customer creation and persisted; never re-derived on request.
	DepositAddress string             `json:"depositAddress"`
	Id             openapi_types.UUID `json:"id"`
}

// Deposit defines model for Deposit.
type Deposit struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — matching Balance's convention.
	Amount     string             `json:"amount"`
	Asset      DepositAsset       `json:"asset"`
	Chain      DepositChain       `json:"chain"`
	Id         openapi_types.UUID `json:"id"`
	ObservedAt time.Time          `json:"observedAt"`

	// Status "pending" for both the observed and safe tiers; "orphaned" once a reorg has evicted the deposit's block (Story 2.4) — Story 2.2's finalized/credited tiers are never surfaced on this endpoint (see tier).
	Status DepositStatus `json:"status"`

	// Tier This deposit's current position in the observed->safe->finalized->credited state machine (AD-6).
	Tier DepositTier `json:"tier"`

	// TxHash The on-chain transaction hash the deposit was observed in.
	TxHash string `json:"txHash"`
}

// DepositAsset defines model for Deposit.Asset.
type DepositAsset string

// DepositChain defines model for Deposit.Chain.
type DepositChain string

// DepositStatus "pending" for both the observed and safe tiers; "orphaned" once a reorg has evicted the deposit's block (Story 2.4) — Story 2.2's finalized/credited tiers are never surfaced on this endpoint (see tier).
type DepositStatus string

// DepositTier This deposit's current position in the observed->safe->finalized->credited state machine (AD-6).
type DepositTier string

// DepositsResponse defines model for DepositsResponse.
type DepositsResponse struct {
	Deposits []Deposit `json:"deposits"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number. Signed from this customer's own perspective: negative when debited, positive when credited.
	Amount    string             `json:"amount"`
	Asset     TransactionAsset   `json:"asset"`
	Chain     TransactionChain   `json:"chain"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// Status "completed" for most cause types (e.g. "internal_transfer"); "credited" for a "deposit_credit" cause type (Story 2.2), the same terminal state as the underlying deposit.
	Status string `json:"status"`

	// Type The journal entry's cause type, verbatim (e.g. "internal_transfer").
	Type string `json:"type"`
}

// TransactionAsset defines model for Transaction.Asset.
type TransactionAsset string

// TransactionChain defines model for Transaction.Chain.
type TransactionChain string

// TransactionsResponse defines model for TransactionsResponse.
type TransactionsResponse struct {
	// NextCursor Opaque page marker for the next page. Absent when this is the last page.
	NextCursor   *string       `json:"nextCursor,omitempty"`
	Transactions []Transaction `json:"transactions"`
}

// Transfer defines model for Transfer.
type Transfer struct {
	Amount                string             `json:"amount"`
	Asset                 TransferAsset      `json:"asset"`
	Chain                 TransferChain      `json:"chain"`
	CreatedAt             time.Time          `json:"createdAt"`
	DestinationCustomerId openapi_types.UUID `json:"destinationCustomerId"`
	Id                    openapi_types.UUID `json:"id"`
	SourceCustomerId      openapi_types.UUID `json:"sourceCustomerId"`
}

// TransferAsset defines model for Transfer.Asset.
type TransferAsset string

// TransferChain defines model for Transfer.Chain.
type TransferChain string

// TransferRequest defines model for TransferRequest.
type TransferRequest struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — matching Balance's convention. Must be a positive integer.
	Amount                string               `json:"amount"`
	Asset                 TransferRequestAsset `json:"asset"`
	Chain                 TransferRequestChain `json:"chain"`
	DestinationCustomerId openapi_types.UUID   `json:"destinationCustomerId"`
	SourceCustomerId      openapi_types.UUID   `json:"sourceCustomerId"`
}

// TransferRequestAsset defines model for TransferRequest.Asset.
type TransferRequestAsset string

// TransferRequestChain defines model for TransferRequest.Chain.
type TransferRequestChain string

// UnsupportedTokenObservation defines model for UnsupportedTokenObservation.
type UnsupportedTokenObservation struct {
	// Amount The transfer's raw on-chain amount, in the unsupported token's own base units (decimals unknown to this platform) — encoded as a string, never a JSON number, matching Balance's convention.
	Amount      string                           `json:"amount"`
	BlockNumber int64                            `json:"blockNumber"`
	Chain       UnsupportedTokenObservationChain `json:"chain"`

	// ContractAddress The ERC-20 token contract address that emitted the Transfer log — not in token_registry at the time this was observed, hence "unsupported" (Story 2.3, FR11).
	ContractAddress string `json:"contractAddress"`

	// DepositAddress The known deposit address the unsupported transfer landed on.
	DepositAddress string             `json:"depositAddress"`
	Id             openapi_types.UUID `json:"id"`
	ObservedAt     time.Time          `json:"observedAt"`

	// TxHash The on-chain transaction hash the transfer was observed in.
	TxHash string `json:"txHash"`
}

// UnsupportedTokenObservationChain defines model for UnsupportedTokenObservation.Chain.
type UnsupportedTokenObservationChain string

// UnsupportedTokenObservationsResponse defines model for UnsupportedTokenObservationsResponse.
type UnsupportedTokenObservationsResponse struct {
	Observations []UnsupportedTokenObservation `json:"observations"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateCustomerParams defines parameters for CreateCustomer.
type CreateCustomerParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListCustomerTransactionsParams defines parameters for ListCustomerTransactions.
type ListCustomerTransactionsParams struct {
	// Cursor Opaque page marker returned as nextCursor by a previous call. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// PageSize Maximum number of transactions to return. Defaults to 20; values above 100 are clamped to 100.
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateTransferParams defines parameters for CreateTransfer.
type CreateTransferParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTransferJSONRequestBody defines body for CreateTransfer for application/json ContentType.
type CreateTransferJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a customer and provision its per-asset accounts
	// (POST /customers)
	CreateCustomer(w http.ResponseWriter, r *http.Request, params CreateCustomerParams)
	// Get a customer's own attributes, including its deposit address
	// (GET /customers/{id})
	GetCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Query a customer's current balance for each supported asset and chain
	// (GET /customers/{id}/balances)
	GetCustomerBalances(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List a customer's pending deposits
	// (GET /customers/{id}/deposits)
	GetCustomerDeposits(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List a customer's transaction history, newest first
	// (GET /customers/{id}/transactions)
	ListCustomerTransactions(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCustomerTransactionsParams)
	// Move balance from one customer to another, ledger-only, no chain interaction
	// (POST /transfers)
	CreateTransfer(w http.ResponseWriter, r *http.Request, params CreateTransferParams)
	// List every recorded unsupported-token observation, for manual operator triage
	// (GET /unsupported-token-observations)
	GetUnsupportedTokenObservations(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCustomerParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomer operation middleware
func (siw *ServerInterfaceWrapper) GetCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerBalances operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerBalances(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerBalances(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerDeposits operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerDeposits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerDeposits(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCustomerTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListCustomerTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomerTransactionsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomerTransactions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTransfer operation middleware
func (siw *ServerInterfaceWrapper) CreateTransfer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTransferParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransfer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUnsupportedTokenObservations operation middleware
func (siw *ServerInterfaceWrapper) GetUnsupportedTokenObservations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUnsupportedTokenObservations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/customers", wrapper.CreateCustomer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}", wrapper.GetCustomer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/balances", wrapper.GetCustomerBalances)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/deposits", wrapper.GetCustomerDeposits)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/transactions", wrapper.ListCustomerTransactions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/transfers", wrapper.CreateTransfer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/unsupported-token-observations", wrapper.GetUnsupportedTokenObservations)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvdchu5cn6VrsmpslgZUpSs493VXmll+Rwna3sjeZMLy3E1B00S1gwwBjCUeVyqykPkCfMkqQYwPyRH",
	"FO1dr+w9vlGRnAHQ6J+vf/UhyXRRakXK2eT4Q1KiwYIcGf/tqaCi1I5Utvx3WvIvUiXHyZxQkEnSRGFB",
	"yXH3tSG/lyaG3lXSkEiOnakoTWw2pwJ5A7cseYl1RqpZcnNzUz/0B/6EOaqMPCVGl2ScJP8ArSXHH0hV",
	"RXL8KiE3T9KksiJLXqfru6bJpN1IkM2MLJ3UTPtT5WhGBiZoCSolnYW9a5Iw1QbOXv49hUdDQZksMI9P",
	"+cGvF49PBymQyrQgAWgBIZwF//c//wuKFmQA4d8uXjwHVRUTMv53pwEXWgqY5hrdoyMoDWXSSq0g19aO",
	"LlXSQ3o2R+Zye1UmNUkTNBPpTFX03Pemy/FXcYc0Mq1lRrtQT95S5vi0yHF7TrbUyvawPq72n6Wjwn/4",
	"i6Fpcpz8y36rPvtRjvu1EG+a49AYXG6Q2WzcR9dpZZ0uyGzSkxlCR+LEq8NUmwJdcpwIdDR0sqA+lgoq",
	"tZXuRAhD1m4qxcs5QRYPfGAh05VyZKaYuQpzOD0/O3l5dghxF8CwDew9OX+UwpPz71I4eTz8fuBlLgUp",
	"JzPMQStgvViCrcpSG0cCzv7zGXjhjOBUF2XFv2mVEaBrzgd/P9YRVAJKMlZaR+LHqGWGhoKMXPiVwOwk",
	"64ImFfj+Z1IzN0+Ojw7TpJCq+7VE58jwbf97/P7VePgDDqcnwyevPxyNb/7SxzQpVhhcVVIkd2mef6UV",
	"0Abn+yT9OLzSY/MFy+F+TbhAl835pajUXjvUgmWs1S0G/LFY9QkGv6N00kRPLJnFx1mLdeiqHiu5TEpS",
	"QqrZZeJZOtFuDm5OUB/iNdbilMBJMvZHuEy0KeeoSFwmUdHBkDYzmKMFWsiMLYC3iHrywMIk19kV7F04",
	"bZZwODoKZlV/PXxgYSoV5vIfJPYzQ0L6Lfg8QENRkLZi6w024ubSAilRaqkc7FkK5A2C9Gqex6slaUNy",
	"L9t5ZR9+SNu5QlYZQ8qB/86WLNUKn4aX1Xj8kJhT8WNzpfi9uRjLgqBAVkKCvZPHw0eDUYfsesskTXi7",
	"O8l//3e0834A1GroNRGcQWUx85TP0c67AoJrtK28pRrtCAlrHimadkNQo3SRwyuKuwU0tritSPDubqvG",
	"obvcVrNxH12/GD3JqXhMDmVu+6jiBz2BUJpIZV0ds2yxyfhIBhAMOuny/lXhhy5MGHmnwPzTetfm5L7L",
	"vmwV5YtD7xFcyJkiAVOji4ABHQ+vr5V3rSVlTi7oGBTNkD/B9ZwUCJqw9aXRguufa6u8T9z/hOhnR1dx",
	"O+yzseTkPIqzNAptHWRYWQLexcIejWYjuPRKaRTmbzyETMlcJgP2AjXj4nqEy9qK3oRHl0lnvxb8Dwep",
	"Bx+LBYEjUzBMRkxE6x9VSpDJl6wJcctbpFPbwibwvdUVEw2knFkyfDeUpLAgM0Eni61X7D2xDwajaTXo",
	"tw6LDQi2Ur7D7rYAoKL37rQyVvc4rBclvqsISpyxczFXZLxgmKG8zD8YwcnEshvzuu8tSAae52jjK72M",
	"7lC3M/h2oeQuAF454Fb+TPtyhxaUvhrrFWSdVD4jqHOip7sZ9K52ryuT0Uft3afbG9vcRvqWaGAHtZ+S",
	"OQ9Jz9eYMMCzyjqYcBzcuJboye/TqXy6jv125fntetOnK7+qJut+qa9IvfDhJH5cqMLOoYb5BxYMXrdB",
	"cliT1qF91Z4Hjg+MQUZX5aKOWajUleKHTgdYLXN0zLSQ6vRoXNqnbuknJac+vXruN1iRlVTu0VG7oBNe",
	"fhrQaeUMZttLLmfnp8PDceAX1Cua8oqbowMqpKtzxNr+IdfRBrXz/Of1bwzNpHVmCej824yngb3dlCWF",
	"OXEeepl0JHaZtCHHwxSenB8cDD5LSWWXOlRQjfVa04aONbxAJXyeO7qnCtCn1Rg+PRFtbv7bMtE1UWxq",
	"bCc3bfxT13juTFG3QNCWqE133to5etqGdndFUysHbt6DMZ6yyki3vODTYk2Y0JA5qZwXoSeDF4WfW0HM",
	"nStDjV+qqe53zD70PvnlaROACjmTDnPwKA/XmOfkGogcwZmvqRaVQ8fQZ3TlCOKFLAQKACs3D3XYppKK",
	"Ctb6FBD6GL6qcnA0GMGZMdpY4Oj//Mkp/HD01+8AyzKP2+yXIbn/17e2gdeQeiePI80nnub/CjT/Emnm",
	"2yVpsiBjw7UPRmNvNyUpLGVynDwcjUcPE2+hc8/f/TpXDSUEbfu8E16RBaXrIjBMtFh6XMS2mDxH/0rG",
	"FJkha0kuOSmWlAvL4Lk4GMGJWobFPtznOH+mtCExAjZHE3W1jv5jkNaecS3dHNjDzUiR8c9kzJFZsz3v",
	"ODJITv3KprKfrnSbXvWrePvK/lo36uY1K3KgzbPpcHzg+wNaOQruvCs8FlqjrHiXRTVEeu1dZfzpSqWe",
	"BMvyaDzecnZXcXanYa2W1EPJTyga6YcEtZDWsln0q/ogkHpwD6Q+i4RpA1ItMJeitlXvvgNhP9wDYeuc",
	"MlRZEkGpEYScTskXc7tWxtT+9V4k/qui9yX5srl3PgaIQSvgdFUUaJaNoXVxwPeSjF6E7iMba0lmGCAW",
	"M9/wsn6TFnn2P0hxwxTPqDenyvJKUISEtrK2HrhwFKsAnTNywkitpysrGF18AgB7T86/G6ykVgHaGwDg",
	"pUy4vlZ94PI3crcji29bM7q2TWsfDdzep74ridkEn/EfCj5fuCUf3QNhz/WaT2JFm8kFKZAC6L20rONf",
	"tuX+je1xvVLdWI/lfJPtjvnPtrBmbX0WvN/t3/ea8hlmc4hvgW9khf5yrJwT5CRmnhgORKSa2TYftY4D",
	"BVhgXoX21MPBCE58vBz6cXKz9sI2vlP5ZT0d9slvsMCGhJAL23S3YYtbIaMeg/jaoWNjnGNb/NJoxjcs",
	"+TNiyX9UnCmtoEndma6tnS2N2PzbykKMCZQIkyq9kNLtrfZCyjm5yqgGn+x6B5wF3gwKpGGSoOnZo4XQ",
	"CIHuxEHbFGJMMVpUWYw+bp8H4LQPlFbDuE3clyEqQqqPhqyPQnKmayFxPaLpK8fstQM/2DwMgJShMZJs",
	"N/iSYvfYpW5sf+1AtNGg71HjtbGrWkiNdn2DpT8jLP0s7VqMsyn4HsxZbyvegjsoYh1CZpjnyzaI8V3d",
	"ocPZjETT8t2LH96Qct5q32qpfAm/E+sYYosJo0q6d5SgzqBi/qLDYW98M3sqc+cTsOX1nAylYDVMK1cZ",
	"Wm2hx8unXq7C4DXmA8CyJPTlLF2gi1fygle6nWnK5qhmZEexKcGAZj/z8MMqfrFIawDrNqf/CBBLd+ht",
	"G++Ogmtp2+IwYe9YGlpIXVlfIxvBi0K6phQ5labT6fa0v2On2hKfhQb7tgnnDQKf4XtZVEXdNeSMuMMz",
	"1rFA7wge0xSr3PnfDsc/hjDbAk70guBgPPYRdpZjUQbdPBiPbyOUL3Eh/0F9pDbNns/qEXqnFnpQ5IWK",
	"wlsrFTywqw0BybnH8v6Kb0H0ILSvwjoQxImKz0Mg+IyOCqbsS2oZsIGWhny1dVI5v3qzIfzN/f2TuL8e",
	"rebs9pqsCwgU/GHd+NrSEjgBlltOdXwvVmeb2MlMpINQcUsjpEOn3T6ATBcFR6rodNHxN1KBVgR7PidI",
	"Q5IwgBJl/E+HekhrZlBVORrplvWEVlN2JD/OPmxrktFrwt6T8yM/Q//Q/z0ajOC57m8DSgshyg6l99u7",
	"DM0M0O/SZfCl35+0WP6+aNgZZrlZ7cuxF7z5jP2Nhj19YXndYW3m/r6MDocfr+nvb6RQYM6RAglfoE8b",
	"4PIqtO/1NQ2pYA2z9QQHp6KhBE3vKsxt1x4u1TcU3iDsInCLfV/LqY2WY7TuJpaKUiSxBiJfV+fHqwtC",
	"plVdSqmfYm4IxRL8Hj7kvqIlRwPXRvpezAoUR8U6PLw/+dUC6lR+8zh3o9YkFgcgvnDP+oyj4qayxZkP",
	"u6xGLzkwU9rNORgLFe2hVjm7Wh1Qwgdeph5CZZfbmbgZeqMbro9n9GahJ+B0OcxpQXnaTC4Mr6Wg2NOq",
	"h5dUYK+fYYa1hNe/ZKX/pxkFG5RAhxIWXfCB2gynmIWJMe3AZjpmBqiWq9zYHHiCk9UJK89BXJ/Oqmeu",
	"5rQ+d+XLaJk2ggRwpgtSWUfoa19+li1muMd1oSwmlHUl3+kqTLO1LYcRXDiZ5+14RxNndOY8AG38Rzsv",
	"3MDiW6ps22Zyks+Y++w0C9Sj+GHYpWHrVi1Yjxm/YL/1xcfn9FF89/8TgarCvDFDcEbiLMq0HqDy4Wd3",
	"dOrVaw4vAzEhOF2l+GedYQ6CFrAndHYVQzJtCfahwCsCU6lBkiaVyeO01fH+fs6L5tq64+/H34/3FwfJ",
	"TfohvuK/vb75/wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
