//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BalanceAsset.
const (
	BalanceAssetEth  BalanceAsset = "eth"
	BalanceAssetUsdc BalanceAsset = "usdc"
)

// Valid indicates whether the value is a known member of the BalanceAsset enum.
func (e BalanceAsset) Valid() bool {
	switch e {
	case BalanceAssetEth:
		return true
	case BalanceAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for BalanceChain.
const (
	BalanceChainArbitrum BalanceChain = "arbitrum"
	BalanceChainBase     BalanceChain = "base"
)

// Valid indicates whether the value is a known member of the BalanceChain enum.
func (e BalanceChain) Valid() bool {
	switch e {
	case BalanceChainArbitrum:
		return true
	case BalanceChainBase:
		return true
	default:
		return false
	}
}

// Defines values for DepositAsset.
const (
	DepositAssetEth  DepositAsset = "eth"
	DepositAssetUsdc DepositAsset = "usdc"
)

// Valid indicates whether the value is a known member of the DepositAsset enum.
func (e DepositAsset) Valid() bool {
	switch e {
	case DepositAssetEth:
		return true
	case DepositAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for DepositChain.
const (
	DepositChainArbitrum DepositChain = "arbitrum"
	DepositChainBase     DepositChain = "base"
)

// Valid indicates whether the value is a known member of the DepositChain enum.
func (e DepositChain) Valid() bool {
	switch e {
	case DepositChainArbitrum:
		return true
	case DepositChainBase:
		return true
	default:
		return false
	}
}

// Defines values for DepositStatus.
const (
	DepositStatusOrphaned DepositStatus = "orphaned"
	DepositStatusPending  DepositStatus = "pending"
)

// Valid indicates whether the value is a known member of the DepositStatus enum.
func (e DepositStatus) Valid() bool {
	switch e {
	case DepositStatusOrphaned:
		return true
	case DepositStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DepositTier.
const (
	DepositTierObserved DepositTier = "observed"
	DepositTierOrphaned DepositTier = "orphaned"
	DepositTierSafe     DepositTier = "safe"
)

// Valid indicates whether the value is a known member of the DepositTier enum.
func (e DepositTier) Valid() bool {
	switch e {
	case DepositTierObserved:
		return true
	case DepositTierOrphaned:
		return true
	case DepositTierSafe:
		return true
	default:
		return false
	}
}

// Defines values for TransactionAsset.
const (
	TransactionAssetEth  TransactionAsset = "eth"
	TransactionAssetUsdc TransactionAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransactionAsset enum.
func (e TransactionAsset) Valid() bool {
	switch e {
	case TransactionAssetEth:
		return true
	case TransactionAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for TransactionChain.
const (
	TransactionChainArbitrum TransactionChain = "arbitrum"
	TransactionChainBase     TransactionChain = "base"
)

// Valid indicates whether the value is a known member of the TransactionChain enum.
func (e TransactionChain) Valid() bool {
	switch e {
	case TransactionChainArbitrum:
		return true
	case TransactionChainBase:
		return true
	default:
		return false
	}
}

// Defines values for TransferAsset.
const (
	TransferAssetEth  TransferAsset = "eth"
	TransferAssetUsdc TransferAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransferAsset enum.
func (e TransferAsset) Valid() bool {
	switch e {
	case TransferAssetEth:
		return true
	case TransferAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for TransferChain.
const (
	TransferChainArbitrum TransferChain = "arbitrum"
	TransferChainBase     TransferChain = "base"
)

// Valid indicates whether the value is a known member of the TransferChain enum.
func (e TransferChain) Valid() bool {
	switch e {
	case TransferChainArbitrum:
		return true
	case TransferChainBase:
		return true
	default:
		return false
	}
}

// Defines values for TransferRequestAsset.
const (
	TransferRequestAssetEth  TransferRequestAsset = "eth"
	TransferRequestAssetUsdc TransferRequestAsset = "usdc"
)

// Valid indicates whether the value is a known member of the TransferRequestAsset enum.
func (e TransferRequestAsset) Valid() bool {
	switch e {
	case TransferRequestAssetEth:
		return true
	case TransferRequestAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for TransferRequestChain.
const (
	TransferRequestChainArbitrum TransferRequestChain = "arbitrum"
	TransferRequestChainBase     TransferRequestChain = "base"
)

// Valid indicates whether the value is a known member of the TransferRequestChain enum.
func (e TransferRequestChain) Valid() bool {
	switch e {
	case TransferRequestChainArbitrum:
		return true
	case TransferRequestChainBase:
		return true
	default:
		return false
	}
}

// Defines values for UnsupportedTokenObservationChain.
const (
	UnsupportedTokenObservationChainArbitrum UnsupportedTokenObservationChain = "arbitrum"
	UnsupportedTokenObservationChainBase     UnsupportedTokenObservationChain = "base"
)

// Valid indicates whether the value is a known member of the UnsupportedTokenObservationChain enum.
func (e UnsupportedTokenObservationChain) Valid() bool {
	switch e {
	case UnsupportedTokenObservationChainArbitrum:
		return true
	case UnsupportedTokenObservationChainBase:
		return true
	default:
		return false
	}
}

// Defines values for WithdrawalAsset.
const (
	WithdrawalAssetEth  WithdrawalAsset = "eth"
	WithdrawalAssetUsdc WithdrawalAsset = "usdc"
)

// Valid indicates whether the value is a known member of the WithdrawalAsset enum.
func (e WithdrawalAsset) Valid() bool {
	switch e {
	case WithdrawalAssetEth:
		return true
	case WithdrawalAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for WithdrawalChain.
const (
	WithdrawalChainArbitrum WithdrawalChain = "arbitrum"
	WithdrawalChainBase     WithdrawalChain = "base"
)

// Valid indicates whether the value is a known member of the WithdrawalChain enum.
func (e WithdrawalChain) Valid() bool {
	switch e {
	case WithdrawalChainArbitrum:
		return true
	case WithdrawalChainBase:
		return true
	default:
		return false
	}
}

// Defines values for WithdrawalStatus.
const (
	Approved         WithdrawalStatus = "approved"
	AwaitingApproval WithdrawalStatus = "awaiting-approval"
	Created          WithdrawalStatus = "created"
)

// Valid indicates whether the value is a known member of the WithdrawalStatus enum.
func (e WithdrawalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case AwaitingApproval:
		return true
	case Created:
		return true
	default:
		return false
	}
}

// Defines values for WithdrawalRequestAsset.
const (
	WithdrawalRequestAssetEth  WithdrawalRequestAsset = "eth"
	WithdrawalRequestAssetUsdc WithdrawalRequestAsset = "usdc"
)

// Valid indicates whether the value is a known member of the WithdrawalRequestAsset enum.
func (e WithdrawalRequestAsset) Valid() bool {
	switch e {
	case WithdrawalRequestAssetEth:
		return true
	case WithdrawalRequestAssetUsdc:
		return true
	default:
		return false
	}
}

// Defines values for WithdrawalRequestChain.
const (
	WithdrawalRequestChainArbitrum WithdrawalRequestChain = "arbitrum"
	WithdrawalRequestChainBase     WithdrawalRequestChain = "base"
)

// Valid indicates whether the value is a known member of the WithdrawalRequestChain enum.
func (e WithdrawalRequestChain) Valid() bool {
	switch e {
	case WithdrawalRequestChainArbitrum:
		return true
	case WithdrawalRequestChainBase:
		return true
	default:
		return false
	}
}

// Defines values for GetWithdrawalFeeEstimateParamsChain.
const (
	Arbitrum GetWithdrawalFeeEstimateParamsChain = "arbitrum"
	Base     GetWithdrawalFeeEstimateParamsChain = "base"
)

// Valid indicates whether the value is a known member of the GetWithdrawalFeeEstimateParamsChain enum.
func (e GetWithdrawalFeeEstimateParamsChain) Valid() bool {
	switch e {
	case Arbitrum:
		return true
	case Base:
		return true
	default:
		return false
	}
}

// Defines values for GetWithdrawalFeeEstimateParamsAsset.
const (
	GetWithdrawalFeeEstimateParamsAssetEth  GetWithdrawalFeeEstimateParamsAsset = "eth"
	GetWithdrawalFeeEstimateParamsAssetUsdc GetWithdrawalFeeEstimateParamsAsset = "usdc"
)

// Valid indicates whether the value is a known member of the GetWithdrawalFeeEstimateParamsAsset enum.
func (e GetWithdrawalFeeEstimateParamsAsset) Valid() bool {
	switch e {
	case GetWithdrawalFeeEstimateParamsAssetEth:
		return true
	case GetWithdrawalFeeEstimateParamsAssetUsdc:
		return true
	default:
		return false
	}
}

// ApproveWithdrawalRequest defines model for ApproveWithdrawalRequest.
type ApproveWithdrawalRequest struct {
	// Actor The operator approving this withdrawal (NFR11) — required and non-empty; this system has no separate operator-identity/auth tier to derive this from.
	Actor string `json:"actor"`

	// Reason The reason for approving this withdrawal (NFR11) — required and non-empty.
	Reason string `json:"reason"`
}

// Balance defines model for Balance.
type Balance struct {
	Asset BalanceAsset `json:"asset"`

	// Balance Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — to avoid float64 precision loss.
	Balance string       `json:"balance"`
	Chain   BalanceChain `json:"chain"`
}

// BalanceAsset defines model for Balance.Asset.
type BalanceAsset string

// BalanceChain defines model for Balance.Chain.
type BalanceChain string

// BalancesResponse defines model for BalancesResponse.
type BalancesResponse struct {
	Balances []Balance `json:"balances"`
}

// Customer defines model for Customer.
type Customer struct {
	CreatedAt time.Time `json:"createdAt"`

	// DepositAddress The customer's counterfactual CREATE2 deposit address (FR6, FR7, AD-8) — identical on every supported EVM chain. Computed once at customer creation and persisted; never re-derived on request.
	DepositAddress string             `json:"depositAddress"`
	Id             openapi_types.UUID `json:"id"`
}

// Deposit defines model for Deposit.
type Deposit struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — matching Balance's convention.
	Amount     string             `json:"amount"`
	Asset      DepositAsset       `json:"asset"`
	Chain      DepositChain       `json:"chain"`
	Id         openapi_types.UUID `json:"id"`
	ObservedAt time.Time          `json:"observedAt"`

	// Status "pending" for both the observed and safe tiers; "orphaned" once a reorg has evicted the deposit's block (Story 2.4) — Story 2.2's finalized/credited tiers are never surfaced on this endpoint (see tier).
	Status DepositStatus `json:"status"`

	// Tier This deposit's current position in the observed->safe->finalized->credited state machine (AD-6).
	Tier DepositTier `json:"tier"`

	// TxHash The on-chain transaction hash the deposit was observed in.
	TxHash string `json:"txHash"`
}

// DepositAsset defines model for Deposit.Asset.
type DepositAsset string

// DepositChain defines model for Deposit.Chain.
type DepositChain string

// DepositStatus "pending" for both the observed and safe tiers; "orphaned" once a reorg has evicted the deposit's block (Story 2.4) — Story 2.2's finalized/credited tiers are never surfaced on this endpoint (see tier).
type DepositStatus string

// DepositTier This deposit's current position in the observed->safe->finalized->credited state machine (AD-6).
type DepositTier string

// DepositsResponse defines model for DepositsResponse.
type DepositsResponse struct {
	Deposits []Deposit `json:"deposits"`
}

// FeeEstimate defines model for FeeEstimate.
type FeeEstimate struct {
	// L1Fee The amortized L1 data-posting fee component, in integer base units (wei), encoded as a string — never a JSON number.
	L1Fee string `json:"l1Fee"`

	// L2Fee The L2 execution fee component, in integer base units (wei), encoded as a string — never a JSON number — matching Balance's convention.
	L2Fee string `json:"l2Fee"`

	// TotalFee l2Fee + l1Fee, in integer base units (wei), encoded as a string — never a JSON number, and never a naive single-number estimate collapsing the two components.
	TotalFee string `json:"totalFee"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number. Signed from this customer's own perspective: negative when debited, positive when credited.
	Amount    string             `json:"amount"`
	Asset     TransactionAsset   `json:"asset"`
	Chain     TransactionChain   `json:"chain"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// Status "completed" for most cause types (e.g. "internal_transfer"); "credited" for a "deposit_credit" cause type (Story 2.2), the same terminal state as the underlying deposit.
	Status string `json:"status"`

	// Type The journal entry's cause type, verbatim (e.g. "internal_transfer").
	Type string `json:"type"`
}

// TransactionAsset defines model for Transaction.Asset.
type TransactionAsset string

// TransactionChain defines model for Transaction.Chain.
type TransactionChain string

// TransactionsResponse defines model for TransactionsResponse.
type TransactionsResponse struct {
	// NextCursor Opaque page marker for the next page. Absent when this is the last page.
	NextCursor   *string       `json:"nextCursor,omitempty"`
	Transactions []Transaction `json:"transactions"`
}

// Transfer defines model for Transfer.
type Transfer struct {
	Amount                string             `json:"amount"`
	Asset                 TransferAsset      `json:"asset"`
	Chain                 TransferChain      `json:"chain"`
	CreatedAt             time.Time          `json:"createdAt"`
	DestinationCustomerId openapi_types.UUID `json:"destinationCustomerId"`
	Id                    openapi_types.UUID `json:"id"`
	SourceCustomerId      openapi_types.UUID `json:"sourceCustomerId"`
}

// TransferAsset defines model for Transfer.Asset.
type TransferAsset string

// TransferChain defines model for Transfer.Chain.
type TransferChain string

// TransferRequest defines model for TransferRequest.
type TransferRequest struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — matching Balance's convention. Must be a positive integer.
	Amount                string               `json:"amount"`
	Asset                 TransferRequestAsset `json:"asset"`
	Chain                 TransferRequestChain `json:"chain"`
	DestinationCustomerId openapi_types.UUID   `json:"destinationCustomerId"`
	SourceCustomerId      openapi_types.UUID   `json:"sourceCustomerId"`
}

// TransferRequestAsset defines model for TransferRequest.Asset.
type TransferRequestAsset string

// TransferRequestChain defines model for TransferRequest.Chain.
type TransferRequestChain string

// UnsupportedTokenObservation defines model for UnsupportedTokenObservation.
type UnsupportedTokenObservation struct {
	// Amount The transfer's raw on-chain amount, in the unsupported token's own base units (decimals unknown to this platform) — encoded as a string, never a JSON number, matching Balance's convention.
	Amount      string                           `json:"amount"`
	BlockNumber int64                            `json:"blockNumber"`
	Chain       UnsupportedTokenObservationChain `json:"chain"`

	// ContractAddress The ERC-20 token contract address that emitted the Transfer log — not in token_registry at the time this was observed, hence "unsupported" (Story 2.3, FR11).
	ContractAddress string `json:"contractAddress"`

	// DepositAddress The known deposit address the unsupported transfer landed on.
	DepositAddress string             `json:"depositAddress"`
	Id             openapi_types.UUID `json:"id"`
	ObservedAt     time.Time          `json:"observedAt"`

	// TxHash The on-chain transaction hash the transfer was observed in.
	TxHash string `json:"txHash"`
}

// UnsupportedTokenObservationChain defines model for UnsupportedTokenObservation.Chain.
type UnsupportedTokenObservationChain string

// UnsupportedTokenObservationsResponse defines model for UnsupportedTokenObservationsResponse.
type UnsupportedTokenObservationsResponse struct {
	Observations []UnsupportedTokenObservation `json:"observations"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Amount string `json:"amount"`

	// ApprovalReason The reason given for approving this withdrawal (Story 3.3, NFR11) — absent for an auto-approved withdrawal or one still awaiting approval.
	ApprovalReason *string `json:"approvalReason,omitempty"`

	// ApprovedAt When this withdrawal was approved (Story 3.3, NFR11) — absent for a withdrawal still awaiting approval.
	ApprovedAt *time.Time `json:"approvedAt,omitempty"`

	// ApprovedBy The operator (or, for an auto-approved withdrawal, absent) who approved this withdrawal (Story 3.3, NFR11) — caller-supplied at approval time, since this system has no separate operator-identity/auth tier.
	ApprovedBy         *string            `json:"approvedBy,omitempty"`
	Asset              WithdrawalAsset    `json:"asset"`
	Chain              WithdrawalChain    `json:"chain"`
	CreatedAt          time.Time          `json:"createdAt"`
	CustomerId         openapi_types.UUID `json:"customerId"`
	DestinationAddress string             `json:"destinationAddress"`
	Id                 openapi_types.UUID `json:"id"`

	// Status "created" is a withdrawal's initial status, immediately superseded in the same request by Story 3.3's policy-check-and-route step — no withdrawal is ever observable at rest in this status via this API. "awaiting-approval" is reached when the requested amount exceeds its (chain, asset)'s configured approval threshold (FR17); "approved" is reached either automatically (amount at or below threshold) or via POST /withdrawals/{id}/approve. Later stories (3.4-3.5) add further status values as they add the transitions that produce them.
	Status WithdrawalStatus `json:"status"`
}

// WithdrawalAsset defines model for Withdrawal.Asset.
type WithdrawalAsset string

// WithdrawalChain defines model for Withdrawal.Chain.
type WithdrawalChain string

// WithdrawalStatus "created" is a withdrawal's initial status, immediately superseded in the same request by Story 3.3's policy-check-and-route step — no withdrawal is ever observable at rest in this status via this API. "awaiting-approval" is reached when the requested amount exceeds its (chain, asset)'s configured approval threshold (FR17); "approved" is reached either automatically (amount at or below threshold) or via POST /withdrawals/{id}/approve. Later stories (3.4-3.5) add further status values as they add the transitions that produce them.
type WithdrawalStatus string

// WithdrawalRequest defines model for WithdrawalRequest.
type WithdrawalRequest struct {
	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — never a JSON number — matching Balance's convention. Must be a positive integer.
	Amount     string                 `json:"amount"`
	Asset      WithdrawalRequestAsset `json:"asset"`
	Chain      WithdrawalRequestChain `json:"chain"`
	CustomerId openapi_types.UUID     `json:"customerId"`

	// DestinationAddress The on-chain address the withdrawal will eventually be sent to. Validated for structural well-formedness only (Story 3.2) — never checked against a denylist or any other pre-signing policy, which is Story 3.3's job.
	DestinationAddress string `json:"destinationAddress"`
}

// WithdrawalRequestAsset defines model for WithdrawalRequest.Asset.
type WithdrawalRequestAsset string

// WithdrawalRequestChain defines model for WithdrawalRequest.Chain.
type WithdrawalRequestChain string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateCustomerParams defines parameters for CreateCustomer.
type CreateCustomerParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListCustomerTransactionsParams defines parameters for ListCustomerTransactions.
type ListCustomerTransactionsParams struct {
	// Cursor Opaque page marker returned as nextCursor by a previous call. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// PageSize Maximum number of transactions to return. Defaults to 20; values above 100 are clamped to 100.
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateTransferParams defines parameters for CreateTransfer.
type CreateTransferParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateWithdrawalParams defines parameters for CreateWithdrawal.
type CreateWithdrawalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetWithdrawalFeeEstimateParams defines parameters for GetWithdrawalFeeEstimate.
type GetWithdrawalFeeEstimateParams struct {
	Chain GetWithdrawalFeeEstimateParamsChain `form:"chain" json:"chain"`
	Asset GetWithdrawalFeeEstimateParamsAsset `form:"asset" json:"asset"`

	// Amount Integer base units (wei for ETH, 6-decimal units for USDC), encoded as a string — matching Balance's convention. Must be a positive integer no larger than a uint256. Validated but not itself a factor in the returned fee: gas cost for a plain transfer or token transfer call does not vary with the transferred amount, so the same fee is returned for any valid amount of a given chain/asset pair.
	Amount string `form:"amount" json:"amount"`
}

// GetWithdrawalFeeEstimateParamsChain defines parameters for GetWithdrawalFeeEstimate.
type GetWithdrawalFeeEstimateParamsChain string

// GetWithdrawalFeeEstimateParamsAsset defines parameters for GetWithdrawalFeeEstimate.
type GetWithdrawalFeeEstimateParamsAsset string

// ApproveWithdrawalParams defines parameters for ApproveWithdrawal.
type ApproveWithdrawalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateTransferJSONRequestBody defines body for CreateTransfer for application/json ContentType.
type CreateTransferJSONRequestBody = TransferRequest

// CreateWithdrawalJSONRequestBody defines body for CreateWithdrawal for application/json ContentType.
type CreateWithdrawalJSONRequestBody = WithdrawalRequest

// ApproveWithdrawalJSONRequestBody defines body for ApproveWithdrawal for application/json ContentType.
type ApproveWithdrawalJSONRequestBody = ApproveWithdrawalRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a customer and provision its per-asset accounts
	// (POST /customers)
	CreateCustomer(w http.ResponseWriter, r *http.Request, params CreateCustomerParams)
	// Get a customer's own attributes, including its deposit address
	// (GET /customers/{id})
	GetCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Query a customer's current balance for each supported asset and chain
	// (GET /customers/{id}/balances)
	GetCustomerBalances(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List a customer's pending deposits
	// (GET /customers/{id}/deposits)
	GetCustomerDeposits(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List a customer's transaction history, newest first
	// (GET /customers/{id}/transactions)
	ListCustomerTransactions(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ListCustomerTransactionsParams)
	// Move balance from one customer to another, ledger-only, no chain interaction
	// (POST /transfers)
	CreateTransfer(w http.ResponseWriter, r *http.Request, params CreateTransferParams)
	// List every recorded unsupported-token observation, for manual operator triage
	// (GET /unsupported-token-observations)
	GetUnsupportedTokenObservations(w http.ResponseWriter, r *http.Request)
	// Request a withdrawal, placing an immediate ledger-only hold on the requested amount
	// (POST /withdrawals)
	CreateWithdrawal(w http.ResponseWriter, r *http.Request, params CreateWithdrawalParams)
	// Query a withdrawal's estimated fee before submitting one
	// (GET /withdrawals/fee-estimate)
	GetWithdrawalFeeEstimate(w http.ResponseWriter, r *http.Request, params GetWithdrawalFeeEstimateParams)
	// Approve an awaiting-approval withdrawal (Story 3.3, FR17, NFR11)
	// (POST /withdrawals/{id}/approve)
	ApproveWithdrawal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ApproveWithdrawalParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCustomerParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomer operation middleware
func (siw *ServerInterfaceWrapper) GetCustomer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerBalances operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerBalances(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerBalances(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerDeposits operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerDeposits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerDeposits(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCustomerTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListCustomerTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomerTransactionsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomerTransactions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTransfer operation middleware
func (siw *ServerInterfaceWrapper) CreateTransfer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTransferParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransfer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUnsupportedTokenObservations operation middleware
func (siw *ServerInterfaceWrapper) GetUnsupportedTokenObservations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUnsupportedTokenObservations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWithdrawal operation middleware
func (siw *ServerInterfaceWrapper) CreateWithdrawal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWithdrawalParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWithdrawal(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWithdrawalFeeEstimate operation middleware
func (siw *ServerInterfaceWrapper) GetWithdrawalFeeEstimate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWithdrawalFeeEstimateParams

	// ------------- Required query parameter "chain" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "chain", r.URL.Query(), &params.Chain, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "chain"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chain", Err: err})
		}
		return
	}

	// ------------- Required query parameter "asset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "asset", r.URL.Query(), &params.Asset, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "asset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset", Err: err})
		}
		return
	}

	// ------------- Required query parameter "amount" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "amount", r.URL.Query(), &params.Amount, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "amount"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "amount", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWithdrawalFeeEstimate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveWithdrawal operation middleware
func (siw *ServerInterfaceWrapper) ApproveWithdrawal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ApproveWithdrawalParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveWithdrawal(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/customers", wrapper.CreateCustomer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}", wrapper.GetCustomer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/balances", wrapper.GetCustomerBalances)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/deposits", wrapper.GetCustomerDeposits)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/customers/{id}/transactions", wrapper.ListCustomerTransactions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/transfers", wrapper.CreateTransfer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/unsupported-token-observations", wrapper.GetUnsupportedTokenObservations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/withdrawals", wrapper.CreateWithdrawal)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/withdrawals/fee-estimate", wrapper.GetWithdrawalFeeEstimate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/withdrawals/{id}/approve", wrapper.ApproveWithdrawal)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3dctvGkn6VLuypslgHpChZcRL5SvFPjncd2ys7JxdRNjUEmuTYwAwyM6DEk3LVPsQ+4T7JVvfMACAJ",
	"UrQSW3LWNy6RBAaNmf75uvub8e9JpstKK1TOJqe/J5UwokSHhj89y7GstEOVLf8Dl/SNVMlpMkeRo0nS",
	"RIkSk9PuZUO6Lk0M/lZLg3ly6kyNaWKzOZaCBnDLim6xzkg1S96/fx9/5AeeVZXRC/xJunluxKUozvG3",
	"Gq1j0Yyu0DiJfKXInDb0R442M7JyUpNob+YIdJlw2oDg0aSagZtLC5fNqHDw4un50dEA/ve//weirCBU",
	"DkqrIZaVWz7099ildVjCXFhQGizS/Lj2EUOZo3LSLQ9F7ebgJBpwGnI0coF+hKnR5ehCJWlSSvUc1czN",
	"k9OjdH0iaM6EpXfoeyX/G0z/4EuNrpPifXfpfg6T3Ij2S3O9nrzFzJHU34lCqAx7Fsha5HVDVZc0GLp5",
	"kia1zbPOQO3rT9qBVt//mXI4QwMTYRFqJZ2Fg0uUPBlP3vwjhQfDHDNZiiL8Sj/8+Prxo0EKqDKd0yxY",
	"EOCfxdOjcIEGBPz765cvQNXlBA1/7zSIhZY5TAst3IMTqAxm0kqtoNDW+nXcED2bC6m6r0qiJmkizEQ6",
	"U5c977s20X6ENExaOxk7Ztyeo620sj1TH+7mv6XDkv/4m8Fpcpr822Fr8IfB8g7jIr5vHieMEcsNMZuB",
	"++R6VFunSzSb8mQGhcP8jNVhqk0pXHKa5MLh0MkS+6Y0x0pb6c7y3KC1/UaRhQfes5DpWjk0U5G5WhTw",
	"6PzJ2ZsnxxBGAeGHgYOn5w9SeHr+dQpnj4ffeFPxJpyJArQC0osl2LqqtHGYw5N//gC8OCN4pMuqpu+0",
	"yhCEa54P/H6kI2RsFRorrcP8YdAyg0PvD+hONky0LngEcRVt8eR4xTTpYyWcQ0Nv+1/jq5/Hw2/FcHo2",
	"fPrL7yfj93/rmzSZr0xwXcs8uU7z+JJ2gTZmvm+lH/tLemy+pHW4XRMuhcvmdFFQatYOtaA11mqLAX+o",
	"r7qBwe+5OmmiJxbN4sOsxTrh6h4ruUgqVLlUs4uEp3SiKUhRiAwPYY21YoocuuxDuEi0qeZCYX6RBEUH",
	"g9rMOATiQmZkATRE0JN7FiaFzt7BwWunzRKORyferOLH43sWplKJQv4L88PMYC55CHoeCINhIW1N1utt",
	"hAMbqrzSUjk4sOjFG/jVi3MeXi1JG5F7p53u7PMf0nZeIauNQeWAP5MlS7UyT8OLejy+jzRT4c/mlcLn",
	"5sVoLRBKQUqIcHD2ePhgMOqIHYdM0oSGu1b8q38IO98CdNSQNRGcEcqKjCWfCzvvLhBcCtuut1SjPV3C",
	"WkQKpt0I1ChdmOEVxd3hNHaErSDw/mEr+qHrwlYzcJ9cTxGfWCdL4XpEKo6eIvZPvii1caQA8PwIcuHE",
	"sNLWkeOZIkIjbUqqJPv934d5ty2+qzjeKuLzY8ArzGrWi48k1Y19rtNOFL2i8xvB34En/8+TNPVYOPyg",
	"BCF0K9WswGF4FQx6AJkuClFZD7IR3KVup64fBK5pnF+UNOhP52X7NPCV0ZMCy8fohCxsn13QDz3JU5pI",
	"ZV1EzTuiQvgpTKP3iq7ov8t/0Q1URl77vvxrHLV5ct/Lvmld1Z3DDyN4LWcKc87ZfBTqYEx9qRjcVZg5",
	"ucBTUDgT9BdczlFBjhPy/2mIIfHrGBduE3ncAH/vCVa2Aw+ylwId4whajVJbB5moLQKNYuEAR7MRXLBS",
	"GiWKXzmITdFcJAPCIXHiwv0CLqIf/9X/dJF0xmvhx/EgZaO1okRwaEoK1CEqC8s/1SpHUyxJE8KQ23xU",
	"sIVN1/pW1yQ0oHJmSe6ukSSFBZqJcLLc+Yr7eJF2zjvxdz0wN2G4XeVr7G5HCFZ45R7VxvaVVl5W4rca",
	"oRIzgjfmHRpeGJpQuo1/GMHZxBKQYt1nC5J+zgthwyW9E92Rbu/w33Ul10GAlQdsnZ9pX/baOqXPxnpz",
	"imSKc9KYlT/bz6D3tXtdmww/aOw+3d4YZpvoO/DoHmo/RbO9jnjnU1b4obYOJpSJNaElRPLbDCo317E/",
	"rjx/XG/6dOVH1dR93uh3qF5yQiM+DKpQcIhu/p4FIy7bNM3fk8bksm6fB44eGEBGV+WCjlmo1TtFPzrt",
	"3WpVCEeT5pPtHo1L+zHwTaA6J/gveICVtZLKPThpb+jAy5s5Oq2cEdnuot+T80fD47GfL4h3NAU+NxcO",
	"sJQuVimi/UOhgw1qx/NP9/9qcCatM0sQzgN9WYaqfTdpTmGOKkO4SDordpG0kON+Clx5/yhFvX0qoV41",
	"1qudGzrWzIVQOVdaRrdUg7xZlevmpZDmzf9YLWRtKTY1tlMdaeJT13iuLZLscEE7UJvuXLU3etrl7a5D",
	"UysP7HuPtoH3YXiKe1uiOL++FTaTC7y2IeYN9D4ZaKc3JjxE5XsViNrpoR8D8+7d2oBWCNbJogBxKSQX",
	"d6KI20JvGOisJzT81GDizlNII5un7yFw996dou1nU/HR3y2v6aUeaJNeN2VpkHQAl3PdvtWey5KJokAz",
	"JK0sJMUy17wRO+YUrCQ3fMO+7GeWgGcfhqk68KcTKW7Ht+8oCvh5uEgoK+yq8j0LUkknQ6Ze2xRkWWIu",
	"hcOC+3FoLObstNvsPvTSYLKERqXuWah0IbPlMJtj9m4oVD40unZkyFgFCNDVRmm56RfCgpgU3NszNK4M",
	"5upFgoUU/vPZq2eU1kfDG0Y19e9lUGRzsgtv7o2YpNLs+gCvMsTcAiM8VqgUWA8HHo1N5azm3n2j/nOD",
	"dq6LHA6enh99zfWRaF6rD0Xp5gT6aqdLwV3NYgkH4bnCkVObYKEv2yEH9B292quXr9/AYTsz9vB3mb8/",
	"DM8ZwXPh0IB12ki0cHB/dDK8P/pqQHADprXh58aZEkWNNpRblnxFE4a5vxKQWmV0XrNJY7na3AmaQoa1",
	"PstJ67Wub6z7+L1XItljQntXV/YhrHxJNG/oPP8MT7gDMXbhcjcwU2xFmpuajWiCwFHY6RH8UxSSvHfO",
	"i2GdqTNXG7oJi2JIImKuaEytyPyiczoedFaH3ROt3UxIZR0IyFEtC2nZSIVagmaTqgwOrZwpWjbv2VK4",
	"nMtsTmbfdXtv9eQjJCDrRJWbmtKm1VCkwKw20i1fEyYN3BUUBs1Z7RjoM1ilm/zXrXhz5yrPHpNqqvut",
	"igu0Z6+eNWXKXM6kE4X3tXBJeMM1ifQInjD3o6ydYDjlo0Z4eQteAvKsc88XaRgfQsEaAw48Q467v0cn",
	"gxE8MUYbC7VFOH/6CL49+epr8u5FGOaw8i2gv7+1TRLuGzTJ4yDzGcv8k5f5VZCZ3i5JkwUa61/7aDTm",
	"7KpCJSqZnCb3R+PR/YRXfc7zexhX0DeatO2rYYh3yLiqCbA6X3ok2pJeAvRaR21TiQWFNgWLoxGcqaW/",
	"mU1HWpAzpQ3mI/BQ3mc0sUYcfGz7DDJHjpIzVATsKP6HTopHelIrcgvJI76zYSClKzzGn/sTofaSwzWe",
	"4/tfSOm9bDxNx+Mj5jFp5dD78O7ivQ25Skty3JV3NUKy9q5O/KMVRhHmtJYn4/GOZ3cVZ38Z1jqOPZJ8",
	"J/Jm9X0bo5SWG6L9qj7woh7dgqg/BMG0AakW5JmjrXKRxwv27S0Itj5TBmsb8iXy9nI6RSaddK2MpP3q",
	"Vlb8R4VXFTK9h0sUBpCclvfTdVkKs2wMresHmPNGCTizJMlYKzRD72JFxsQ8y4O0noeBJUk8w15AlBV1",
	"jsEltP3X9fIWgR4FwjkjJ+Sp9XTlDvIuXCYmzPz1YAUXedfeOAC6lQTXl6rPuXyPbrtnYUI0edeWDs24",
	"ZDsD+rpS96bzGX9S53PHLfnkFgR7oddiEimar0DJHPBKWtLxu22535M9rvMZGuuhhJvtjuafbGHN2vos",
	"+LDLM+415Scim0O4Cphw53mwgV+BUGA+Y2ECd8q2XQtKNDH3qSQDqfuDEZwxwvS8wR5SENn4XrnTetOE",
	"EyVvgY0IPm+y6X6k8K0uI9K1P3fXsUE734VfGs344kv+ir7kP2vKlFa8SWTQRmsnS0My/7b/FDCByj2j",
	"vteldDmgvS7lHF1tVOOf7DpTlxa8ITSnnvHccItFU8vrMqNb6hD5FF+S8uhjO2+Z0j7eVxOGCeOSiwou",
	"ldGQZRRSkFy+eojrHnhji0K7MUE0P4aKgTBceuuAL5nvj10iAfdzd0QbROIeNV7bHhIXqdGuL27pr+iW",
	"nku7hnE2F77H56yTz7b4HZGHOkSoqjcghrl/QydmM8wbYuBB+ONXVI6t9q2WiokeHaxjkCzGb6nQvYTT",
	"mEENYueCH/YrUx6nsnCcgC0v52gwBathWrva4CrRMrx82qluDkBUFYr1RgEvvNLt3otsLtQM7Sh2LqQF",
	"+5Epsqv+i5Y0OrAuhfFTOLF0Dwak4XDkQ0tLnoQJRcfK4ELq2nKNbAQvS+maUuRUmg4fkmX/jYJqK3zm",
	"aZi79s5uCPiDuJJlXcaSP2XEnTkjHfPyjuAxTkVdOP7uePyw6dhM9ALhaDxmhJ0Voqy8bh6Nx9sEpZd4",
	"Lf+FfaI2lKCPGhF6ua09XuSlCou3Viq4Z1dpI5Jyj+XtFd/80kOuuQrrIEdKVDgPAR8zOiqYUiyJa0AG",
	"Whnkauukdnz3ZjfnS/j7fxL+erSasttLtM57IB8PIz1qR0vgLGyVifg+X2XAU5CZSAe+4pYGlw6dPtAA",
	"Ml2WhFSF02Un3kjFNJvVPjhUQoYd2bHZPzNC1YUw0i0jj78pOyJvux22NckQNeHg6fkJ7/W9z/+eDEbw",
	"QveTxSIPIJTet3cZGqb4n9Jl4NLvdzpf/rnesEN5fr/aw6Mo+P4j9jea6emD5ZGH1+wOuRsdDu6N9/c3",
	"UihF4Tu6XKBPG8fFKnTI+pr6VDC62cjzpVTUl6Dxt1oUtmsPF+qLF94Q7LWfLYp97UxttByDdTdYquXX",
	"rDqRz6vzw+oiINMqllLir6IwKPIl8BgMud/hktDApZHci1lxxUGxjo9vb/3iAnUqv0VgZ/czou56ZP2B",
	"UHFT2aLMh0JWo5cEzBSzNdJQ0R5qVVCo1d5LMPAycasShdwOL3vIRjdcJ/H2ZqFn4HQ1LHCBRdowF4aX",
	"MsfQ04oUd+Wnl3e6wVrCyxd5LqVQsCEJdCShpWs4lVOR+X0F2oHNdMgMmKnSnY1NWjycrfLweQbFOoc/",
	"MvPnuM7O5zJapk2OOVCmC1JZh4JrX0x9ChnuaSyUhYQyVvKdrj3tqW05jOA1k2cbekeDMzo8DxA2HAji",
	"qTg8xVuqbLuY28lHzH32Yoz3KL4nuzTTulML1jHjHY5bdx6f4wfNO++cFaoWRcvEdkaKGXo30mFrbsfu",
	"58hC2X4yKn3pt5E7kFzhEVmGlevS0Y8HpyCuyQA4Adho2ouFkIUn1YagwPV/NlBPgGVa63pIZ0vclhII",
	"8nxSBUumuSyEtXIaVjkFvBKZK5ZQyHfs4uL+22YfSMoU3Mr59kCTLUyw0OQldCtDfBXOG0qtcAkFisUa",
	"OyGcsrU1sYjEpsly9WyThxCZfTTAxGiRZ8IfIiEMQrHOuL3PjFtPnuoipNg8kNbXB/amJn4KOmJfDtXZ",
	"H3JHs6hNRu8nzqM6U9TjcdpfG3N92JoTAeUJoiJDyf76SZboNQZmmEsbamAd9Yfx1bAyOJVXmMPJeDjH",
	"KzJbAiFkyv72L/nZH6iSfcm6PuV7n23E2L0TL379dj/WADK9QOODW8AHsYzc+aoqan9JPDBnZd/cFPHi",
	"zmOx87jKK9vXyF36aNxuP+pmdN676m1J7BoiO5wiDrFztlRvSvdIlxOpAqDYOLGJcIG79rSpCJu8KXoI",
	"cnAWNlUw8+CFzvFZOCIRRzNh45lXj5o5Phik8J2w2DAVvhf2lZEZvjQiK5Aif45VoZeRndB3hNKMUqZ4",
	"jNKlros8bNVreoyckpK7nSHhIV1K52Ju9vyoPWeJ7EoapDTaag/UWn1geCSKS7G0bQsOr0i7JCE/QUDO",
	"Ulrs5igN2LqMyWA424m3kjnNqWutGucgWZvjcUAvVnaKNYRS7+igVk4WDeY5DuVqf+SJgKo2mEKtmvMg",
	"UyCH4vUo47Mk2RAeknVxdiot+xaH25gcbdDvHlrW3wld7yaGrRrbu6EfcnZp/zPiNpDrn7Fzm9BmW/Nj",
	"bJG68VYowvkFaa/xblVALZU7/upBd1tQdJrSWSymIGDKR+nG+kajslPEU7aZTNu4wdcnN82WdR2ifvsN",
	"2VHbHFwIs2yDcbzIdFy87eQz5C1kx2amAdx7lBH8uyaJO77E4y9OwLxm9q5+3Pyz/9nPH7Mn3LWQLQSh",
	"le2nbSibIqZgq4KSYfIQpFDPj9kTd/2TvT1U/awLjhnA8PqQdflGvkc1DWUjoO5VAM3XeGxMdjU8GkcN",
	"v+PQ907BCk8kHs1Ga5CgazcZR3gRj6QgB7JW4PQVlIacfCBoyTobgX3cLfngxsiPntVoKYqtn4EyuFBb",
	"2Jrb9R0mONUGwdaTGI612iwxrWwI3rF9rLPNd+W8Aq779u+bdnplS3MKhZ7NIixoT3iIRbB7FtihHjpZ",
	"onWirA7DuRC5NMjFn4DSuvFbX8Yz0kfw5manCLA3Db7cbmx+kyvIMCQYfsE2qO/hInqTmrGNcnjlaO0r",
	"g0OGGGyzIQ8Z0oRgDoUspQcOkcVi58JgPvRmEoqIpc6xGIzgHN9i5gKkjSM1BzOwA1D+WXxo28qu+ELX",
	"ORycjE8OT8bfDjrEfFnQxUoPddUHVDbO8P9EXK27UTfa+j8Y7FU+Gt9C+Sjupf/8ikTaxGsP+b83CIap",
	"TTgk5ksNp7+Gs7LL/a5VcVaRWSzgheoMpXbrx93AQSzVRFVOw8k4oex+fY3nMgSLZkgjMhzwfTcpKt39",
	"8kfwUhwV1qPxtqN6np4ffR0P7An/cUvYvs8+vbtx/+dfyL3653uPvyrkc52JAnJcwEGus3eBEKQtwiGU",
	"4h2CqdWAMkRThL3+p4eHBd0019adfjP+Zny4OErI6/tL+NMv7/8vAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
